# Noncompliant [[sc=1;ec=48]] {{The value "specsyncdemo.visualstudio.com/mycalculator" does not match reg-ex.}} 
@tfs:specsyncdemo.visualstudio.com/MyCalculator 
Feature: My feature allowed tags custom...
  Blabla...

  # Noncompliant [[sc=3;ec=10]] {{The value "abc" does not match reg-ex.}}
  @tc:abc 
  Scenario: Scenario 1 allowed tags custom
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

@tc:1234 @us:1234 @bug:1234 @uid:MySpecialNameforUIDxxxxxxxXXXXXXXXXXXXXX @tfs:https://specsyncdemo.visualstudio.com/MyCalculator
  Scenario: Scenario 2 allowed tags custom
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
